const RAW_DOMESTIC_INDICES = [
  "RELIANCE.NS",
  "TCS.NS",
  "HDFCBANK.NS",
  "BHARTIARTL.NS",
  "ICICIBANK.NS",
  "SBIN.NS",
  "INFY.NS",
  "LICI.NS",
  "ITC.NS",
  "LT.NS",
  "HINDUNILVR.NS",
  "BAJFINANCE.NS",
  "HCLTECH.NS",
  "SUNPHARMA.NS",
  "MARUTI.NS",
  "KOTAKBANK.NS",
  "TATAMOTORS.NS",
  "ULTRACEMCO.NS",
  "AXISBANK.NS",
  "NTPC.NS",
  "BAJAJFINSV.NS",
  "ONGC.NS",
  "WIPRO.NS",
  "M&M.NS",
  "POWERGRID.NS",
  "ADANIPORTS.NS",
  "TITAN.NS",
  "ASIANPAINT.NS",
  "NESTLEIND.NS",
  "COALINDIA.NS",
  "JSWSTEEL.NS",
  "TATASTEEL.NS",
  "TECHM.NS",
  "HDFCLIFE.NS",
  "SBILIFE.NS",
  "INDUSINDBK.NS",
  "GRASIM.NS",
  "HINDALCO.NS",
  "EICHERMOT.NS",
  "ADANIENT.NS",
  "BAJAJ-AUTO.NS",
  "CIPLA.NS",
  "DRREDDY.NS",
  "BPCL.NS",
  "BRITANNIA.NS",
  "HEROMOTOCO.NS",
  "SHRIRAMFIN.NS",
  "DIVISLAB.NS",
  "APOLLOHOSP.NS",
  "TATACONSUM.NS",
  "ADANIGREEN.NS",
  "ADANIPOWER.NS",
  "DLF.NS",
  "PIDILITIND.NS",
  "SIEMENS.NS",
  "VEDL.NS",
  "GODREJCP.NS",
  "ICICIPRULI.NS",
  "AMBUJACEM.NS",
  "INDIGO.NS",
  "TORNTPHARM.NS",
  "TVSMOTOR.NS",
  "ABB.NS",
  "BANKBARODA.NS",
  "CANBK.NS",
  "CHOLAFIN.NS",
  "DABUR.NS",
  "GAIL.NS",
  "HAL.NS",
  "HAVELLS.NS",
  "IOC.NS",
  "IRCTC.NS",
  "JINDALSTEL.NS",
  "LODHA.NS",
  "MCDOWELL-N.NS",
  "NMDC.NS",
  "PFC.NS",
  "PNB.NS",
  "RECLTD.NS",
  "SAIL.NS",
  "SAMVARDBL.NS",
  "SRF.NS",
  "TRENT.NS",
  "UNIONBANK.NS",
  "UPL.NS",
  "VARUNBEV.NS",
  "ZYDUSLIFE.NS",
  "BOSCHLTD.NS",
  "COLPAL.NS",
  "CONCOR.NS",
  "CUMMINSIND.NS",
  "MOTHERSON.NS",
  "NAUKRI.NS",
  "OBEROIRLTY.NS",
  "PAGEIND.NS",
  "PETRONET.NS",
  "POLYCAB.NS",
  "UBL.NS",
  "VOLTAS.NS"
];

const RAW_GLOBAL_INDICES = [
  // INDIA (34)
  { symbol: "^NSEI", name: "NIFTY 50", region: "India" },
  { symbol: "^BSESN", name: "SENSEX", region: "India" },
  { symbol: "^NSEBANK", name: "NIFTY BANK", region: "India" },
  { symbol: "^NSMIDCP", name: "NIFTY NEXT 50", region: "India" },
  { symbol: "^CNX100", name: "NIFTY 100", region: "India" },
  { symbol: "^CNX200", name: "NIFTY 200", region: "India" },
  { symbol: "NIFTY500.NS", name: "NIFTY 500", region: "India" },
  { symbol: "^NSEMDCP50", name: "NIFTY MIDCAP 50", region: "India" },
  { symbol: "^CRSMID", name: "NIFTY MIDCAP 100", region: "India" },
  { symbol: "NIFTYMIDCAP150.NS", name: "NIFTY MIDCAP 150", region: "India" },
  { symbol: "^CNXSC", name: "NIFTY SMALLCAP 100", region: "India" },
  { symbol: "NIFTYSMLCAP250.NS", name: "NIFTY SMALLCAP 250", region: "India" },
  { symbol: "^CNXSMLCAP50", name: "NIFTY SMALLCAP 50", region: "India" },
  { symbol: "^INDIAVIX", name: "INDIA VIX", region: "India" },
  { symbol: "^CNXCMDT", name: "NIFTY COMMODITIES", region: "India" },
  { symbol: "^CNXCPSE", name: "NIFTY CPSE", region: "India" },
  { symbol: "^CNXIT", name: "NIFTY IT", region: "India" },
  { symbol: "^CNXAUTO", name: "NIFTY AUTO", region: "India" },
  { symbol: "^CNXPHARMA", name: "NIFTY PHARMA", region: "India" },
  { symbol: "^CNXFMCG", name: "NIFTY FMCG", region: "India" },
  { symbol: "NIFTY_FIN_SERVICE.NS", name: "NIFTY FINANCIAL SERVICES", region: "India" },
  { symbol: "^CNXMETAL", name: "NIFTY METAL", region: "India" },
  { symbol: "^CNXENERGY", name: "NIFTY ENERGY", region: "India" },
  { symbol: "^CNXREALTY", name: "NIFTY REALTY", region: "India" },
  { symbol: "^CNXPSUBANK", name: "NIFTY PSU BANK", region: "India" },
  { symbol: "^CNXMEDIA", name: "NIFTY MEDIA", region: "India" },
  { symbol: "^CNXINFRA", name: "NIFTY INFRASTRUCTURE", region: "India" },
  { symbol: "^CNXCONSUM", name: "NIFTY CONSUMPTION", region: "India" },
  { symbol: "NIFTYMICROCAP250.NS", name: "NIFTY MICROCAP 250", region: "India" },
  { symbol: "NIFTY_PVT_BANK.NS", name: "NIFTY PRIVATE BANK", region: "India" },
  { symbol: "^CNXMNC", name: "NIFTY MNC", region: "India" },
  { symbol: "^CNXDIVOP", name: "NIFTY DIVIDEND OP 50", region: "India" },
  { symbol: "^CNXPSE", name: "NIFTY PSE", region: "India" },
  { symbol: "^CNXSERVICE", name: "NIFTY SERVICES SECTOR", region: "India" },

  // USA (10)
  { symbol: "^GSPC", name: "S&P 500", region: "US" },
  { symbol: "^IXIC", name: "NASDAQ", region: "US" },
  { symbol: "^DJI", name: "Dow Jones", region: "US" },
  { symbol: "^RUT", name: "Russell 2000", region: "US" },
  { symbol: "^NDX", name: "NASDAQ 100", region: "US" },
  { symbol: "^VIX", name: "VIX", region: "US" },
  { symbol: "^DJT", name: "Dow Jones Transport", region: "US" },
  { symbol: "^DJU", name: "Dow Jones Utility", region: "US" },
  { symbol: "^NYA", name: "NYSE Composite", region: "US" },
  { symbol: "^TNX", name: "Treasury Yield 10 Years", region: "US" },

  // EUROPE (10)
  { symbol: "^GDAXI", name: "DAX", region: "Europe" },
  { symbol: "^FCHI", name: "CAC 40", region: "Europe" },
  { symbol: "^FTSE", name: "FTSE 100", region: "Europe" },
  { symbol: "^STOXX50E", name: "EURO STOXX 50", region: "Europe" },
  { symbol: "^SSMI", name: "Swiss Market", region: "Europe" },
  { symbol: "^FTSEMIB", name: "FTSE MIB", region: "Europe" },
  { symbol: "^IBEX", name: "IBEX 35", region: "Europe" },
  { symbol: "^BFX", name: "BEL 20", region: "Europe" },
  { symbol: "^AEX", name: "AEX Index", region: "Europe" },
  { symbol: "^OMXSP", name: "OMX Stockholm 30", region: "Europe" },

  // CANADA
  { symbol: "^GSPTSE", name: "S&P/TSX Composite", region: "Canada" },

  // AUSTRALIA
  { symbol: "^AXJO", name: "S&P/ASX 200", region: "Australia" },

  // CHINA
  { symbol: "000001.SS", name: "SSE Composite", region: "China" },
  { symbol: "399001.SZ", name: "Shenzhen Component", region: "China" },

  // BRAZIL
  { symbol: "^BVSP", name: "IBOVESPA", region: "Brazil" },

  // MEXICO
  { symbol: "^MXX", name: "IPC Index", region: "Mexico" },

  // SINGAPORE
  { symbol: "^STI", name: "Straits Times Index", region: "Singapore" },

  // JAPAN (3)
  { symbol: "^N225", name: "Nikkei 225", region: "Japan" },
  { symbol: "^TOPX", name: "TOPIX Index", region: "Japan" },
  { symbol: "^JQINDEX", name: "JASDAQ Index", region: "Japan" },

  // HONG KONG (3)
  { symbol: "^HSI", name: "Hang Seng", region: "Hong Kong" },
  { symbol: "^HSCE", name: "China Enterprises", region: "Hong Kong" },
  { symbol: "^HSTECH", name: "Hang Seng Tech", region: "Hong Kong" },

  // TAIWAN (2)
  { symbol: "^TWII", name: "TAIEX", region: "Taiwan" },
  { symbol: "^TWOII", name: "Taiwan OTC Index", region: "Taiwan" },

  // SOUTH KOREA (2)
  { symbol: "^KS11", name: "KOSPI", region: "South Korea" },
  { symbol: "^KQ11", name: "KOSDAQ Index", region: "South Korea" },

  // CRYPTO (16)
  { symbol: "BTC-USD", name: "Bitcoin", region: "Crypto" },
  { symbol: "ETH-USD", name: "Ethereum", region: "Crypto" },
  { symbol: "SOL-USD", name: "Solana", region: "Crypto" },
  { symbol: "XRP-USD", name: "Ripple", region: "Crypto" },
  { symbol: "DOGE-USD", name: "Dogecoin", region: "Crypto" },
  { symbol: "ADA-USD", name: "Cardano", region: "Crypto" },
  { symbol: "AVAX-USD", name: "Avalanche", region: "Crypto" },
  { symbol: "DOT-USD", name: "Polkadot", region: "Crypto" },
  { symbol: "LINK-USD", name: "Chainlink", region: "Crypto" },
  { symbol: "TRX-USD", name: "TRON", region: "Crypto" },
  { symbol: "LTC-USD", name: "Litecoin", region: "Crypto" },
  { symbol: "XLM-USD", name: "Stellar", region: "Crypto" },
  { symbol: "HBAR-USD", name: "Hedera", region: "Crypto" },
  { symbol: "SHIB-USD", name: "Shiba Inu", region: "Crypto" },
  { symbol: "ATOM-USD", name: "Cosmos", region: "Crypto" },
  { symbol: "ETC-USD", name: "Ethereum", region: "Crypto" },

  // FOREX (14)
  { symbol: "EURUSD=X", name: "EUR/USD", region: "Forex" },
  { symbol: "GBPUSD=X", name: "GBP/USD", region: "Forex" },
  { symbol: "USDJPY=X", name: "USD/JPY", region: "Forex" },
  { symbol: "USDCHF=X", name: "USD/CHF", region: "Forex" },
  { symbol: "USDCAD=X", name: "USD/CAD", region: "Forex" },
  { symbol: "AUDUSD=X", name: "AUD/USD", region: "Forex" },
  { symbol: "NZDUSD=X", name: "NZD/USD", region: "Forex" },
  { symbol: "USDINR=X", name: "USD/INR", region: "Forex" },
  { symbol: "USDHKD=X", name: "USD/HKD", region: "Forex" },
  { symbol: "USDCNY=X", name: "USD/CNY", region: "Forex" },
  { symbol: "EURGBP=X", name: "EUR/GBP", region: "Forex" },
  { symbol: "EURJPY=X", name: "EUR/JPY", region: "Forex" },
  { symbol: "GBPJPY=X", name: "GBP/JPY", region: "Forex" },
  { symbol: "AUDJPY=X", name: "AUD/JPY", region: "Forex" },

  // COMMODITIES (8)
  { symbol: "GC=F", name: "Gold", region: "Commodities" },
  { symbol: "SI=F", name: "Silver", region: "Commodities" },
  { symbol: "CL=F", name: "Crude Oil", region: "Commodities" },
  { symbol: "BZ=F", name: "Brent Oil", region: "Commodities" },
  { symbol: "NG=F", name: "Natural Gas", region: "Commodities" },
  { symbol: "HG=F", name: "Copper", region: "Commodities" },
  { symbol: "PL=F", name: "Platinum", region: "Commodities" },
  { symbol: "PA=F", name: "Palladium", region: "Commodities" }
];

const RAW_MARKET_UNIVERSE: Record<string, string[]> = {
  india: [
    // --- Nifty 50 (Large Cap) ---
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "BHARTIARTL.NS", "SBIN.NS", "LICI.NS", "ITC.NS", "HINDUNILVR.NS",
    "LT.NS", "BAJFINANCE.NS", "HCLTECH.NS", "MARUTI.NS", "SUNPHARMA.NS",
    "ADANIENT.NS", "KOTAKBANK.NS", "AXISBANK.NS", "TITAN.NS", "ULTRACEMCO.NS",
    "ONGC.NS", "NTPC.NS", "TATAMOTORS.NS", "JSWSTEEL.NS", "COALINDIA.NS",
    "ASIANPAINT.NS", "ADANIPORTS.NS", "POWERGRID.NS", "NESTLEIND.NS", "M&M.NS",
    "HDFCLIFE.NS", "ADANIPOWER.NS", "TATASTEEL.NS", "SBILIFE.NS", "IOC.NS",
    "GRASIM.NS", "TECHM.NS", "WIPRO.NS", "HINDALCO.NS", "INDUSINDBK.NS",
    "JIOFIN.NS", "HAL.NS", "BEL.NS", "BPCL.NS", "CIPLA.NS",
    "EICHERMOT.NS", "HEROMOTOCO.NS", "BRITANNIA.NS", "SHRIRAMFIN.NS", "DIVISLAB.NS",
    "APOLLOHOSP.NS", "LTIM.NS", "BAJAJ-AUTO.NS", "HINDZINC.NS", "TATACONSUM.NS",

    // --- Nifty Next 50 & Midcap ---
    "TATAPOWER.NS", "ASHOKLEY.NS", "BHEL.NS", "YESBANK.NS", "SAIL.NS",
    "PFC.NS", "REC.NS", "POLYCAB.NS", "GMRINFRA.NS", "TATAELXSI.NS",
    "DLF.NS", "IRFC.NS", "RVNL.NS", "HUDCO.NS", "IRCTC.NS",
    "ZOMATO.NS", "PAYTM.NS", "NYKAA.NS", "LICHSGFIN.NS", "UNIONBANK.NS",
    "CANBK.NS", "PNB.NS", "BOB.NS", "INDIANB.NS", "UCOBANK.NS",
    "CENTRALBK.NS", "IOB.NS", "MAHABANK.NS", "PSB.NS", "SJVN.NS",
    "NHPC.NS", "NLCINDIA.NS", "BOSCHLTD.NS", "MRF.NS", "BALKRISIND.NS",
    "DEEPAKNTR.NS", "TATACOMM.NS", "PERSISTENT.NS", "KPITTECH.NS", "COFORGE.NS",
    "MPHASIS.NS", "LTTS.NS", "DIXON.NS", "SYNGENE.NS", "AUBANK.NS",
    "BANDHANBNK.NS", "FEDERALBNK.NS", "IDFCFIRSTB.NS", "KARURVYSYA.NS", "CUB.NS",
    "TRENT.NS", "ABFRL.NS", "PAGEIND.NS", "METROBRAND.NS", "BATAINDIA.NS",
    "RELAXO.NS", "DEVYANI.NS", "WESTLIFE.NS", "JUBILFOOD.NS", "SAPPHIRE.NS",
    "ALKEM.NS", "AARTIIND.NS", "COROMANDEL.NS", "PIIND.NS", "UPL.NS",
    "SUMICHEM.NS", "BAYERCROP.NS", "ATUL.NS", "SRF.NS", "GNFC.NS",
    "GSFC.NS", "CHAMBLFERT.NS", "FACT.NS", "RCFL.NS", "NFL.NS",
    "VOLTAS.NS", "BLUESTARCO.NS", "HAVELLS.NS", "CROMPTON.NS", "KEI.NS",
    "SUPREMEIND.NS", "ASTRAL.NS", "FINCABLES.NS", "KAIARICER.NS", "SOMANYCERA.NS",
    "CENTURYPLY.NS", "GREENPANEL.NS", "PIDILITIND.NS", "BERGERPAINT.NS", "KANSAINER.NS",
    "AKZOINDIA.NS", "INDIGO.NS", "SPICEJET.NS", "GATI.NS", "BLUEDART.NS",
    "CONCOR.NS", "GPPL.NS", "GEESHIP.NS", "SCI.NS", "VBL.NS",
    "JINDALSTEL.NS", "NMDC.NS", "NATIONALUM.NS", "HINDCOPPER.NS",
    "VEDL.NS", "HEG.NS", "GRAPHITE.NS", "APLAPOLLO.NS", "JSL.NS",
    "WELCORP.NS", "RATNAMANI.NS", "MASTEK.NS", "SONACOMS.NS",

    // --- Select Active Smallcaps & Nifty 500 ---
    "ZENSARTECH.NS", "SUZLON.NS", "HFCL.NS", "NBCC.NS", "TRIDENT.NS",
    "IRCON.NS", "PPLPHARMA.NS", "EASEMYTRIP.NS", "J&KBANK.NS",
    "IFCI.NS", "RITES.NS", "ENGINERSIN.NS", "TEJASNET.NS", "ITI.NS",
    "ROUTE.NS", "TANLA.NS", "NUCLEUS.NS", "NEWGEN.NS", "BSOFT.NS",
    "CYIENT.NS", "DATAPATTERNS.NS", "MTARTECH.NS", "GENUSPOWER.NS", "HBLPOWER.NS",
    "KEC.NS", "POWERMECH.NS", "TECHNOE.NS", "VAIBHAVGBL.NS", "ECLERX.NS",
    "REDINGTON.NS", "MAPMYINDIA.NS", "AFFLE.NS", "IDEA.NS", "INDUSTOWER.NS",
    "ROLEXRINGS.NS", "CLEAN.NS", "SUPRAJIT.NS", "MNDA.NS", "PRICOL.NS",
    "FIEMIND.NS", "WELSPUNLIV.NS", "GHCL.NS", "NCC.NS", "KNRCON.NS",
    "PNCINFRA.NS", "ZEEL.NS", "SUNTV.NS", "UJJIVANSFB.NS", "MUTHOOTFIN.NS",
    "MANAPPURAM.NS", "CHOLAFIN.NS", "M&MFIN.NS", "CREDITACC.NS", "IBULHSGFIN.NS",
    "CANFINHOME.NS", "ANGELONE.NS", "MCX.NS", "CAMS.NS", "CDSL.NS",
    "BSE.NS", "UTIAMC.NS", "HDFCAMC.NS", "CESC.NS", "COCHINSHIP.NS",
    "CUMMINSIND.NS", "EXIDEIND.NS", "GAIL.NS", "GLENMARK.NS", "GODREJCP.NS",
    "GODREJPROP.NS", "HINDPETRO.NS", "IRB.NS", "JSWENERGY.NS", "L&TFH.NS",
    "LAURUSLABS.NS", "LUPIN.NS", "MARICO.NS", "MAXHEALTH.NS", "MRPL.NS",
    "OBEROIRLTY.NS", "PVRINOX.NS", "RADICO.NS", "RBLBANK.NS", "SOBHA.NS",
    "STARHEALTH.NS", "TATACHEM.NS", "TORENTPOWER.NS", "VGUARD.NS", "VIPIND.NS"
  ],
  usa: [
    // --- Dow 30 & Mega Cap Tech ---
    "AAPL", "MSFT", "NVDA", "AMZN", "GOOGL", "GOOG", "META", "TSLA", "BRK-B", "LLY",
    "AVGO", "V", "JPM", "UNH", "MA", "WMT", "HD", "PG", "XOM", "JNJ",
    "COST", "ORCL", "MRK", "BAC", "CVX", "KO", "NFLX", "AMD", "PEP", "ADBE",
    "TMO", "WFC", "CRM", "QCOM", "ABT", "GE", "PM", "INTC", "TXN", "MS",
    "IBM", "AMGN", "DIS", "CAT", "PFE", "COP", "ISRG", "CMCSA", "HON", "SPGI",
    "NEE", "NOW", "AXP", "AMAT", "LOW", "BKNG", "NKE", "RTX", "PLTR", "TJX",

    // --- S&P 500 / NASDAQ 100 Selected Liquids ---
    "ADP", "MDLZ", "ANET", "INTU", "GILD", "LRCX", "MU", "PANW", "REGN", "VRTX",
    "CSCO", "C", "SYK", "DE", "BSX", "CI", "MELI", "EL", "ABNB", "ADI",
    "LMT", "GEHC", "KLAC", "SLB", "FI", "WM", "NOC", "CDNS", "MCK", "SNPS",
    "HCA", "EMR", "EOG", "AON", "MAR", "COF", "PGR", "ORLY", "CTAS", "T",
    "DHR", "MDT", "ZTS", "MCO", "ECL", "APH", "FTNT", "PCAR", "ROST", "PAYX",
    "MNST", "ADSK", "CEG", "FIS", "HUM", "KDP", "MCHP", "O", "PEG", "SBUX",
    "SRE", "TRV", "WDAY", "AEP", "CRWD", "EXC", "GD", "ITW", "MET", "PH",
    "PSA", "RSG", "SO", "UTX", "WELL", "ACN", "DD", "EIX", "EQIX", "FE",
    "KMI", "MPC", "OKE", "PCG", "PPG", "PSX", "VLO", "WEC", "XEL", "YUM",

    // --- High Beta & Active Nasdaq/Mid-Caps ---
    "SNAP", "PINS", "PATH", "ROKU", "DKNG", "HOOD", "AFRM", "SOFI", "U", "DOCU",
    "ETSY", "LCID", "RIVN", "SE", "SHOP", "SQ", "COIN", "MARA", "RIOT",
    "CLSK", "MSTR", "AI", "C3.AI", "DWAC", "DJT", "UPST", "OPEN", "LMND", "PTON",
    "GME", "AMC", "BB", "NOK", "NVAX", "BNTX", "MRNA", "CRSP", "EDIT", "BEAM",
    "NTLA", "SG", "WING", "SHAK", "SGRA", "CAVA", "BYND", "OTLY", "ROOT", "LFLY",

    // --- Select Active S&P Additions & Russell 2000 ---
    "MMM", "AOS", "AES", "AFL", "A", "APD", "AKAM", "ALB", "ARE", "ALGN",
    "ALLE", "LNT", "ALL", "MO", "AMCR", "AEE", "AMT", "AMP", "AME", "BK",
    "AAL", "AAON", "ABG", "ABCB", "ACAD", "ACHC", "ACIW", "ACLS", "ADC", "ADTN",
    "AEIS", "AEO", "AFG", "AGCO", "AGO", "AGR", "AHL", "AIT", "AL", "ALEX"
  ],
  japan: [
    // Nikkei 225 Major Representative Constituents (Using numeric codes + .T)
    "7203.T", "6758.T", "9984.T", "8306.T", "9432.T", "8035.T", "6861.T", "6098.T",
    "4502.T", "7267.T", "6501.T", "9983.T", "4063.T", "6902.T", "8058.T", "9101.T",
    "6701.T", "7751.T", "6367.T", "4911.T", "6503.T", "9022.T", "8411.T", "8316.T",
    "8001.T", "8031.T", "6954.T", "4503.T", "7201.T", "9020.T", "6702.T", "7974.T",
    "2914.T", "4519.T", "9735.T", "6981.T", "4568.T", "8801.T", "8802.T", "9021.T",
    "9501.T", "9502.T", "9503.T", "9201.T", "9202.T", "9104.T", "9107.T", "8267.T",
    "3382.T", "7269.T", "7270.T", "7011.T", "7012.T", "7013.T", "6301.T", "6302.T",
    "1801.T", "1802.T", "1803.T", "1812.T", "1925.T", "1928.T", "2502.T", "2503.T",
    "2802.T", "3407.T", "3402.T", "3861.T", "4005.T", "4188.T", "4507.T", "4578.T",
    "4689.T", "4901.T", "5019.T", "5020.T", "5108.T", "5201.T", "5333.T", "5401.T",
    "5411.T", "5713.T", "5802.T", "6178.T", "6273.T", "6471.T", "6473.T", "6504.T",
    "6506.T", "6645.T", "6703.T", "6724.T", "6752.T", "6762.T", "6841.T", "6920.T",
    "6971.T", "6976.T", "7202.T", "7205.T", "7261.T", "7272.T", "7731.T", "7733.T",
    "7741.T", "7911.T", "7912.T", "8002.T", "8015.T", "8053.T", "8308.T", "8309.T",
    "8354.T", "8418.T", "8591.T", "8601.T", "8604.T", "8725.T", "8750.T", "8766.T",
    "8830.T", "9001.T", "9005.T", "9007.T", "9008.T", "9009.T", "9041.T", "9042.T",
    "9064.T", "9301.T", "9433.T", "9434.T", "9504.T", "9505.T", "9506.T", "9507.T",
    "9508.T", "9509.T", "9531.T", "9532.T", "9602.T", "9613.T", "9766.T", "9989.T",
    "1332.T", "1605.T", "1721.T", "1963.T", "2002.T", "2269.T", "2282.T", "2432.T",
    "2531.T", "2801.T", "2871.T", "3086.T", "3099.T", "3101.T", "3103.T", "3289.T",
    "3401.T", "3863.T", "4021.T", "4042.T", "4043.T", "4183.T", "4208.T", "4324.T",
    "4452.T", "4506.T", "4523.T", "4543.T", "4661.T", "4704.T", "5202.T", "5214.T",
    "5301.T", "5406.T", "5703.T", "5706.T", "5711.T", "5714.T", "5901.T", "6103.T",
    "6113.T", "6305.T", "6326.T", "6361.T", "6472.T", "6508.T", "6753.T", "6770.T",
    "6857.T", "7003.T", "7004.T", "7205.T", "7262.T", "7269.T", "7752.T", "7832.T",
    "8012.T", "8028.T", "8252.T", "8253.T", "8279.T", "8331.T", "8355.T", "8628.T",
    "8630.T", "8804.T", "9006.T", "9062.T", "9412.T", "9513.T", "9684.T", "9984.T"
  ],
  hongkong: [
    // Hang Seng Index constituents
    "0700.HK", "9988.HK", "1299.HK", "0005.HK", "3690.HK", "9618.HK", "1810.HK", "2318.HK",
    "0388.HK", "1211.HK", "0941.HK", "2015.HK", "2331.HK", "0267.HK", "0960.HK", "1093.HK",
    "1109.HK", "2007.HK", "1928.HK", "2020.HK", "0288.HK", "0016.HK", "0002.HK", "0101.HK",
    "1113.HK", "0012.HK", "0083.HK", "0151.HK", "1880.HK", "1024.HK", "1177.HK", "0857.HK",
    "0386.HK", "2628.HK", "3988.HK", "0939.HK", "1398.HK", "2388.HK", "1088.HK", "2600.HK",
    "0003.HK", "0006.HK", "0011.HK", "0027.HK", "0066.HK", "0175.HK", "0291.HK", "0322.HK",
    "0669.HK", "0688.HK", "0762.HK", "0813.HK", "0823.HK", "0868.HK", "0883.HK", "0968.HK",
    "0992.HK", "1038.HK", "1044.HK", "1114.HK", "1119.HK", "1199.HK", "1378.HK", "1800.HK",
    "1883.HK", "1918.HK", "1929.HK", "1997.HK", "2009.HK", "2202.HK", "2313.HK", "2314.HK",
    "2319.HK", "2328.HK", "2688.HK", "2899.HK", "3311.HK", "3323.HK", "3328.HK", "3333.HK",
    "3888.HK", "3968.HK", "6030.HK", "6185.HK", "6618.HK", "6862.HK", "6869.HK", "9868.HK",
    "9888.HK", "9961.HK", "9999.HK", "0001.HK", "0004.HK", "0010.HK", "0017.HK", "0019.HK",
    "0020.HK", "0052.HK", "0083.HK", "0107.HK", "0142.HK", "0144.HK", "0168.HK", "0177.HK",
    "0200.HK", "0220.HK", "0270.HK", "0315.HK", "0330.HK", "0345.HK", "0354.HK", "0358.HK",
    "0371.HK", "0384.HK", "0410.HK", "0511.HK", "0522.HK", "0551.HK", "0576.HK", "0590.HK"
  ],
  uk: [
    // FTSE 100 Selected Liquids
    "SHEL.L", "AZN.L", "HSBC.L", "ULVR.L", "BP.L", "GSK.L", "RIO.L", "DGE.L",
    "BATS.L", "BARC.L", "LLOY.L", "VOD.L", "NG.L", "AAL.L", "REL.L", "PRU.L",
    "GLEN.L", "TSCO.L", "RR.L", "AV.L", "NWG.L", "BT-A.L", "EZJ.L", "IAG.L",
    "MKS.L", "SDR.L", "ASC.L", "BOO.L", "PSON.L", "SGE.L", "ABF.L", "ADM.L",
    "AHT.L", "AUTO.L", "BA.L", "BDEV.L", "BKG.L", "CNA.L", "CPG.L", "CRH.L",
    "CTEC.L", "ENT.L", "EXPN.L", "FLTR.L", "FRAS.L", "GDN.L", "HLMA.L", "HLN.L",
    "IMB.L", "INF.L", "IHG.L", "IAG.L", "KGF.L", "LAND.L", "LGEN.L", "MNG.L",
    "MNDI.L", "NXT.L", "OCDO.L", "PHNX.L", "PSN.L", "RKT.L", "RS1.L", "SBRY.L",
    "SGC.L", "SMIN.L", "SMT.L", "SN.L", "SPX.L", "SSE.L", "STAN.L", "STJ.L",
    "TW.L", "UTG.L", "UU.L", "WPP.L", "WTB.L",

    // FTSE 250 Selected Liquids
    "AO.L", "ASHM.L", "ASL.L", "BAB.L", "BALF.L", "BBY.L", "BCG.L", "BDEV.L",
    "BKG.L", "BME.L", "BYG.L", "CAPC.L", "CBG.L", "CHEM.L", "CHG.L", "CLIG.L",
    "CLI.L", "CMCX.L", "CRST.L", "DRX.L", "DPLM.L", "DWF.L", "ESNT.L", "FCAM.L",
    "FDM.L", "FGP.L", "FIFS.L", "FSV.L", "FXPO.L", "GAMES.L", "GCP.L", "GENG.L",
    "GNS.L", "GRA.L", "GRG.L", "GRI.L", "HAS.L", "HAYS.L", "HBR.L", "HHI.L",
    "HIK.L", "HL.L", "HMCH.L", "HOME.L", "HOC.L", "HTG.L", "IAP.L", "IBST.L",
    "ICP.L", "IDX.L", "IGG.L", "IMI.L", "INCH.L", "INDV.L", "INF.L", "INPP.L",
    "INSE.L", "IWG.L", "JDW.L", "JLG.L", "JTC.L", "KAZ.L", "KGF.L", "KMR.L",
    "LMP.L", "LRE.L", "MAB.L", "MCT.L", "MNDY.L", "MUT.L", "NETW.L", "NEX.L",
    "NMC.L", "NXG.L", "OPG.L", "OSB.L", "OXB.L", "PAGE.L", "PTEC.L", "PHP.L",
    "PMP.L", "PNL.L", "POLR.L", "PPHE.L", "PRV.L", "PSN.L", "PYC.L", "QLT.L",
    "RAT.L", "REDD.L", "RIVER.L", "RKT.L", "RMA.L", "RNDY.L", "RRE.L", "RTO.L",
    "SAGA.L", "SAFE.L", "SCT.L", "SDY.L", "SEN.L", "SFOR.L", "SHI.L", "SIG.L",
    "SIV.L", "SJP.L", "SLI.L", "SMWH.L", "SN.L", "SOCO.L", "SPI.L", "SPX.L",
    "SRT.L", "SSP.L", "STA.L", "SVS.L", "SVT.L", "SYNT.L", "TATE.L", "TCG.L",
    "TET.L", "THRL.L", "TIFS.L", "TMPL.L", "TPK.L", "TRA.L", "TRG.L", "TRST.L",
    "TT.L", "TUI.L", "TYMN.L", "ULVR.L", "UKW.L", "VCP.L", "VES.L", "VIT.L",
    "VLE.L", "VNC.L", "VOX.L", "VP.L", "VPC.L", "VSVS.L", "WJG.L", "WKP.L",
    "WLD.L", "WOS.L", "WPG.L", "WPS.L", "WTB.L", "WTE.L", "XAR.L", "ZGP.L"
  ],
  germany: [
    // DAX Constituents
    "SAP.DE", "SIE.DE", "ALV.DE", "BMW.DE", "DTE.DE", "MUV2.DE", "BAS.DE", "BAYN.DE",
    "VOW3.DE", "DHL.DE", "MRK.DE", "IFX.DE", "HEI.DE", "CON.DE", "RWE.DE", "EOAN.DE",
    "HFG.DE", "PUM.DE", "ADS.DE", "TKA.DE", "CBK.DE", "DBK.DE", "DB1.DE", "HNR1.DE",
    "1COV.DE", "FME.DE", "FRE.DE", "MTX.DE", "ZAL.DE", "SY1.DE", "AIR.DE", "BEI.DE",
    "DTG.DE", "ENR.DE", "MBG.DE", "PAH3.DE", "QIAG.DE", "RHM.DE", "SDF.DE", "SHL.DE",

    // MDAX Constituents / Liquid Mid-caps
    "BOSS.DE", "EVK.DE", "FPE3.DE", "G1A.DE", "HAG.DE", "HOT.DE", "JUN3.DE", "KGX.DE",
    "KCO.DE", "LEG.DE", "NDX1.DE", "NEM.DE", "O2D.DE", "PSM.DE", "P1Z.DE", "RHK.DE",
    "SAX.DE", "SGL.DE", "SHA.DE", "SMHN.DE", "SZG.DE", "TEG.DE", "TKA.DE", "UTDI.DE",
    "VAR1.DE", "WCH.DE", "WAF.DE", "SOW.DE", "NDA.DE", "MOR.DE", "KU2.DE", "KBX.DE",
    "GFT.DE", "GLJ.DE", "FRA.DE", "EVT.DE", "ELG.DE", "DWNG.DE", "DUP.DE", "DRW3.DE",
    "DEQ.DE", "COP.DE", "COK.DE", "CLS.DE", "B4B.DE", "ARL.DE", "AM3D.DE", "ADJ.DE"
  ]
};

export const DOMESTIC_INDICES = Array.from(new Set(RAW_DOMESTIC_INDICES));

export const GLOBAL_INDICES = Array.from(
  new Map(RAW_GLOBAL_INDICES.map(item => [item.symbol, item])).values()
);

export const MARKET_UNIVERSE = Object.fromEntries(
  Object.entries(RAW_MARKET_UNIVERSE).map(([key, val]) => [key, Array.from(new Set(val))])
);
