import { ShieldAlert } from "lucide-react";

export default function Disclosures() {
  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex items-center gap-4 border-b border-slate-200 dark:border-slate-800 pb-6">
        <div className="p-3 rounded-2xl bg-amber-50 dark:bg-amber-500/10 text-amber-600 dark:text-amber-400">
          <ShieldAlert className="h-8 w-8" />
        </div>
        <div>
          <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white">Risk Disclosures</h1>
          <p className="text-xs text-slate-400 mt-1">Regulatory & SEBI Compliance</p>
        </div>
      </div>

      {/* Content */}
      <div className="glass-panel p-8 space-y-6 text-sm text-slate-650 dark:text-slate-300 leading-relaxed border-amber-500/15">
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 dark:text-white">1. Algorithmic Processing Disclaimer</h2>
          <p>
            Sentiment indices are generated by computer algorithms extracting variables from public news. They do not constitute human financial advice. Historical tracking performances do not offer guarantees of future index trends.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 dark:text-white">2. SEBI Compliance Notice</h2>
          <p>
            FinPulse AI is not a SEBI-registered portfolio management or certified investment consultancy. The metrics and indices displayed are for educational and computational analysis only.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-slate-900 dark:text-white">3. Investment Risk Warning</h2>
          <p>
            Securities trading contains substantial risk. You should check with a licensed and registered investment advisor before executing trades based on any sentiment indicators.
          </p>
        </section>
      </div>
    </div>
  );
}
